import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Undoubtedly Thomas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Undoubtedly Thomas</h1>
      </main>
    </>
  );
};

export default Home;
